### ISSUE TITLE
Polling Source Path Type is not being stored in the state correctly

### ISSUE THREAD

**Issue by agupta94** [terraform-providers/terraform-provider-sumologic#43] opened 2020-07-03 21:14 UTC
Code:
```
path {
    type            = "S3BucketPathExpression"
    bucket_name     = "xyz"
    path_expression = "a/*"
}
```

State File:
```
"path": [
   {
       "bucket_name": "xyx",
       "limit_to_namespaces": [],
       "limit_to_regions": [],
       "path_expression": "a/*",
       "tag_filters": [],
       "type": ""
   }
],
```

Hence every time terraform plans, following change pops up -
```
~ path {
        bucket_name         = "xyz"
        limit_to_namespaces = []
        limit_to_regions    = []
        path_expression     = "a/*"
      + type                = "S3BucketPathExpression"
}
```

`Terraform version: 0.12.26`

**Comment by mccartney** [comment] 2020-07-05 19:13
Seems like a duplicate of #39

**Closed** 2020-07-08 18:22 UTC
